import os
import resend
from typing import List

def get_api_key_for_recipient(recipient_email):
    """
    The 'Smart Dispatcher'.
    Matches the recipient to the correct Sandbox API Key.
    """
    # 1. Load the Map from Environment Variables
    # Format: { "email_address": "api_key" }
    key_map = {
        os.getenv("EMAIL_CISCO"): os.getenv("RESEND_API_KEY_CISCO"),
        os.getenv("EMAIL_RAUL"): os.getenv("RESEND_API_KEY_RAUL"),
        os.getenv("EMAIL_DAVID"): os.getenv("RESEND_API_KEY_DAVID")
    }
    
    # 2. Return the matching key, or None if not found
    return key_map.get(recipient_email)

def send_email_report(ticker: str, analysis_content: str, recipients: List[str] = None):
    if recipients is None:
        # Default list of everyone
        recipients = [os.getenv("EMAIL_CISCO"), os.getenv("EMAIL_RAUL"), os.getenv("EMAIL_DAVID")]
        # Filter out None values in case one isn't set
        recipients = [r for r in recipients if r]
    results = []
    
    for email in recipients:
        # 🟢 THE HACK: Pick the specific key for this person
        user_key = get_api_key_for_recipient(email)
        
        if not user_key:
            print(f"⚠️ No API Key found for {email}. Skipping.")
            results.append("Skipped (No Key)")
            continue
            
        # Set the key for THIS specific transaction
        resend.api_key = user_key
        
        try:
            # HTML Formatting
            html_content = f"""
            <h1>🔎 PrimoGreedy Report: {ticker}</h1>
            <p>{analysis_content.replace(chr(10), '<br>')}</p>
            <hr>
            <small>Generated by AI Agent  (Value Investor Mode)</small>
            """

            params = {
                "from": "PrimoGreedy <onboarding@resend.dev>", # Sandbox default
                "to": [email], # Send individually to avoid Key conflicts
                "subject": f"Analyze: {ticker} - Verdict Inside",
                "html": html_content
            }

            email_id = resend.Emails.send(params)
            print(f"✅ Email sent to {email} using their specific Key!")
            results.append("Sent")
            
        except Exception as e:
            print(f"❌ Failed to send to {email}: {e}")
            results.append("Failed")

    return f"Processed {len(results)} emails."

