import os
import resend

def send_email_report(ticker: str, report: str):
    """
    Sends an email alert using Resend.
    """
    api_key = os.getenv("RESEND_API_KEY")
    target_email = os.getenv("TARGET_EMAIL") # We will set this in Hugging Face Secrets

    if not api_key or not target_email:
        return "⚠️ Email skipped: Missing API Key or Target Email."

    resend.api_key = api_key

    # Format the email body (Convert newlines to HTML breaks)
    html_body = f"""
    <h1>PrimoGreedy Report: {ticker}</h1>
    <p><strong>Status:</strong> PASSED FIREWALL</p>
    <hr>
    <div style="font-family: monospace; white-space: pre-wrap;">
    {report}
    </div>
    <hr>
    <p><em>Generated by your AI Agent.</em></p>
    """

    params = {
        "from": "PrimoGreedy <onboarding@resend.dev>", # Default testing domain
        "to": [target_email],
        "subject": f"💰 Trade Alert: {ticker} Analysis",
        "html": html_body
    }

    try:
        email = resend.Emails.send(params)
        return f"📧 Email sent! (ID: {email.get('id')})"
    except Exception as e:
        return f"⚠️ Email failed: {str(e)}"