import os
import re
import requests
import yfinance as yf
from dotenv import load_dotenv
from src.finance_tools import check_financial_health
from src.email_utils import send_email_report
from src.global_router import MARKET_CONFIG, normalize_ticker, get_official_filing_link

load_dotenv()

# --- 1. BRAVE SEARCH DISCOVERY ENGINE ---
def brave_search_scout(query):
    """
    Uses Brave API to find web discussions about stocks.
    Returns the combined text of titles and descriptions.
    """
    api_key = os.getenv("BRAVE_API_KEY")
    if not api_key:
        print("⚠️ Brave API Key missing. Returning empty.")
        return ""

    url = "https://api.search.brave.com/res/v1/web/search"
    headers = {"X-Subscription-Token": api_key}
    
    # We look for recent discussions (past month) to get fresh ideas
    params = {"q": query, "count": 10, "freshness": "pm"} 
    
    try:
        response = requests.get(url, headers=headers, params=params)
        data = response.json()
        
        # Combine all text into one big blob for the regex hunter
        combined_text = ""
        results = data.get("web", {}).get("results", [])
        for r in results:
            combined_text += f"{r['title']} {r['description']} "
            
        return combined_text
    except Exception as e:
        print(f"❌ Brave Search Error: {e}")
        return ""

def extract_tickers(text, region):
    """
    Uses Regex to find stock patterns like $ABCD, (LON: ABC), or just CAPS.
    Smartly applies the regional suffix.
    """
    found_tickers = set()
    
    # 1. Regex for CashTags (High Signal): $AAPL, $TSLA
    cashtags = re.findall(r'\$([A-Za-z]{2,5})', text)
    for t in cashtags:
        found_tickers.add(t.upper())

    # 2. Regex for Regional specific patterns (e.g., "LON:RR")
    if region == "UK":
        uk_tags = re.findall(r'LON:\s?([A-Za-z]{2,5})', text)
        found_tickers.update(uk_tags)
    elif region == "CANADA":
        ca_tags = re.findall(r'TSX:\s?([A-Za-z]{2,5})', text)
        found_tickers.update(ca_tags)

    # 3. Clean and Normalize (Add .L, .TO, etc)
    normalized = []
    suffix = MARKET_CONFIG[region]['suffix']
    
    for t in found_tickers:
        clean_t = t.strip().upper()
        # Avoid common false positives
        if clean_t in ["IPO", "CEO", "YTD", "USD", "GBP", "ETF", "THE", "FOR", "AND"]:
            continue
            
        # Add suffix if missing
        if suffix and not clean_t.endswith(suffix):
            clean_t = f"{clean_t}{suffix}"
            
        normalized.append(clean_t)
        
    return list(set(normalized)) # Remove duplicates

# --- 2. MAIN EXECUTION LOOP ---
def run_global_hunt():
    print("🌍 Starting Agentic Global Scout (Brave Powered)...")
    report_html = "<h1>🌍 Daily Agentic Scout Report</h1>"
    report_html += "<p><i>Generated by scraping real-time market discussions via Brave Search.</i></p>"
    
    gems_found = False
    
    # Specific Search Queries for each region
    search_queries = {
        "USA": "undervalued microcap stocks reddit 2026 buy list",
        "UK": "best aim stocks to buy 2026 undervalued ukinvesting",
        "CANADA": "tsx venture deep value stocks mining reddit",
        "AUSTRALIA": "asx small cap gems hotcopper undervalued"
    }

    for region, config in MARKET_CONFIG.items():
        query = search_queries.get(region)
        print(f"🕵️ Scout Searching {region}: '{query}'")
        
        # A. DISCOVER (Brave)
        raw_text = brave_search_scout(query)
        candidates = extract_tickers(raw_text, region)
        
        print(f"   ↳ Found {len(candidates)} potential tickers: {candidates}")
        
        region_gems = []
        for ticker in candidates:
            try:
                # B. ANALYZE (Graham/Buffett Logic)
                # We do a quick check to ensure ticker is valid first
                stock = yf.Ticker(ticker)
                price = stock.info.get('currentPrice')
                
                if not price: 
                    continue # Invalid ticker found by Regex

                # The Value Filter
                health = check_financial_health(ticker)
                
                # Filter: Must Pass Graham OR have Margin of Safety
                if health['status'] == "PASS" or health.get('metrics', {}).get('margin_of_safety', 'N/A') != "N/A":
                    link = get_official_filing_link(ticker, region)
                    gems_found = True
                    
                    # Highlight Margin of Safety in Green if positive
                    safety = health['metrics'].get('margin_of_safety', 'N/A')
                    color = "green" if "%" in str(safety) and "-" not in str(safety) else "black"
                    
                    region_gems.append(f"""
                        <li style="margin-bottom: 10px;">
                            <b>{ticker}</b> ({stock.info.get('shortName', 'Unknown')})<br>
                            Price: {price} {config['currency']}<br>
                            Verdict: {health['reason']}<br>
                            Safety Margin: <span style="color:{color}; font-weight:bold;">{safety}</span><br>
                            <a href="{link}">Verify at {config['gov_source']}</a>
                        </li>
                    """)
            except Exception as e:
                # Common to have errors with random regex tickers
                continue
        
        if region_gems:
            report_html += f"<h2>📍 {region} Discovery</h2><ul>" + "".join(region_gems) + "</ul>"
        else:
            report_html += f"<h2>📍 {region}</h2><p>Scouted {len(candidates)} tickers, but none met Graham's strict criteria.</p>"

    # --- EMAIL DISPATCH ---
    recipients = [os.getenv("EMAIL_CISCO"), os.getenv("EMAIL_JAMES")]
    recipients = [r for r in recipients if r]
    
    print(f"📧 Sending Agentic Report to: {recipients}")
    send_email_report("Agentic Scout Report", report_html, recipients)

if __name__ == "__main__":
    run_global_hunt()